spring:
   profiles:
      active: dev

---
spring:
   profiles: dev
   application: 
       name: microservicecloud-config-client

server:
   port: 8001

eureka:
   client:
      service-url:
         defaultZone: http://eureka-dev.com:7001/eureka/

---

spring:
   profiles: test
   application: 
       name: microservicecloud-config-client

server:
   port: 8002

eureka:
   client:
      service-url:
         defaultZone: http://eureka-test.com:7001/eureka/